language: php
dist: xenial

# Adjust the version of PHP to match your production environment.
# Making this version number greater than the production environment can have unintended consequences
# including a non-functional prod environment.
php: "7.4"

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - ROOT_DIR=$TRAVIS_BUILD_DIR

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
  
services:
- mysql


deploy:
   - provider: script
     script: true
     skip_cleanup: true
     on:
       branch: main
       php: 7.4
